FROM rucio/rucio-clients:release-35.6.0

# Rucio.cfg template for IDL
ENV RUCIO_CFG_CLIENT_RUCIO_HOST=https://rucio-server.131.154.98.24.myip.cloud.infn.it:443
ENV RUCIO_CFG_CLIENT_AUTH_HOST=https://rucio-server.131.154.98.24.myip.cloud.infn.it:443
ENV RUCIO_CFG_CLIENT_AUTH_TYPE=userpass

USER root
RUN pip install numpy

# Custom client for IDL
COPY ./IDL /usr/local/bin/IDL
RUN chmod 555 /usr/local/bin/IDL

# Script to edit username, password and account of the rucio.cfg file
COPY ./cred.py /usr/bin/cred.py
RUN chmod 555 /usr/bin/cred.py