apiVersion: batch/v1
kind: CronJob
metadata:
  name: periodic-dump-and-sanity-check
spec:
  schedule: "0 0 * * *"  # Runs every 24 hours at midnight
  jobTemplate:
    spec:
      template:
        spec:
          nodeSelector:
            kubernetes.io/hostname: vnode-7
          containers:
          - name: cron-dump-and-sanity
            image: lucapacioselli/ayradb-dump-sanity:v0.0.1-new
            imagePullPolicy: Always # For testing only
            command: ["/bin/bash"]
            args: ["-c", "idl_dump.py --all && sleep 60 && idl_consistency_check.py"]
            volumeMounts:
            - name: combined-creds
              mountPath: "/etc/config"
              readOnly: true
            - name: dump-output
              mountPath: "/logs/idl"
              readOnly: false  # Allow writing to the log directory
          volumes:
          - name: dump-output
            persistentVolumeClaim:
              claimName: dump-output-pvc  # Ensure this PVC exists in your cluster
          - name: combined-creds
            projected:
              sources:
                - secret:
                    name: server-ayradb-cluster
                - secret:
                    name: server-root-rucio
                - secret:
                    name: rucio-db-creds
          restartPolicy: OnFailure  # Restart the job on failure