 apiVersion: v1
 kind: Pod
 metadata:
   name: init-db
   labels:
     app: rucio
 spec:
   restartPolicy: Never
   containers:
     - name: init
       image: rucio/rucio-init:release-35.6.1 #latest
       imagePullPolicy: Always
       env:
         - name: RUCIO_CFG_DATABASE_DEFAULT
           value: postgresql://rucio:<DB_PASSWORD>@<HELM_RELEASE_DB_NAME>-postgresql/rucio-db # helm install/upgrade <HELM_RELEASE_DB_NAME> bitnami/postgresql -f /path/to/postgres.yaml
         - name: RUCIO_CFG_DATABASE_SCHEMA
           value: test
         - name: RUCIO_CFG_BOOTSTRAP_USERPASS_IDENTITY
           value: <ROOT_USERNAME>
         - name: RUCIO_CFG_BOOTSTRAP_USERPASS_PWD
           value: <ROOT_PASSWORD>
         - name: RUCIO_PRINT_CFG
           value: "true"
