FROM rucio/rucio-clients:release-35.6.1

USER root

##### DUMP ######
# adbc client to run the dump periodically
COPY ./server/adbc-1.0.1-py3-none-any.whl /usr/local/lib/python3.9/site-packages/adbc-1.0.1-py3-none-any.whl
RUN pip install /usr/local/lib/python3.9/site-packages/adbc-1.0.1-py3-none-any.whl
RUN pip install psycopg2-binary
RUN pip install psutil


# Dump utils
COPY ./server/meta-db/idl_utilities.py /usr/local/bin/idl_dump.py
RUN chmod 555 /usr/local/bin/idl_dump.py

# Consistency-check utils
COPY ./server/meta-db/idl_consistency_check.py /usr/local/bin/idl_consistency_check.py
RUN chmod 555 /usr/local/bin/idl_consistency_check.py

##### Rucio catalog and AyraDB consistency check #####
# Rucio.cfg template for IDL
COPY ./client-test/rucio.cfg /opt/rucio/etc/rucio.cfg

# Custom client for IDL
COPY ./client-test/IDL /usr/local/bin/IDL
RUN chmod 555 /usr/local/bin/IDL