# This file can update the JupyterHub Helm chart's default configuration values.
#
# For reference see the configuration reference and default values, but make
# sure to refer to the Helm chart version of interest to you!
#
# Introduction to YAML:     https://www.youtube.com/watch?v=cdLNKUoMc6c
# Chart config reference:   https://zero-to-jupyterhub.readthedocs.io/en/stable/resources/reference.html
# Chart default values:     https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/HEAD/jupyterhub/values.yaml
# Available chart versions: https://hub.jupyter.org/helm-chart/
#

singleuser:
  # use jupyterlab as the default interface 
  defaultUrl: "/lab"
  image:
    # You should replace the "latest" tag with a fixed version from:
    # https://hub.docker.com/r/jupyter/datascience-notebook/tags/
    # Inspect the Dockerfile at:
    # https://github.com/jupyter/docker-stacks/tree/HEAD/datascience-notebook/Dockerfile
    name: lucapacioselli/jupyter4rucio #jupyter/tensorflow-notebook 
    tag: test-v1.0.9 #v1.0.8 #ubuntu-22.04
    pullPolicy: Always 
  # `cmd: null` allows the custom CMD of the Jupyter docker-stacks to be used
  # which performs further customization on startup.
  cmd: null
  lifecycleHooks: 
    postStart:
      exec:
        command: 
        - "sh"
        - "-c"
        - >
          mkdir -p /opt/rucio/etc;
          echo "[client]" >> /opt/rucio/etc/rucio.cfg;
          echo "rucio_host = https://rucio-server.212.189.145.181.myip.cloud.infn.it" >> /opt/rucio/etc/rucio.cfg;
          echo "auth_host = https://rucio-server.212.189.145.181.myip.cloud.infn.it" >> /opt/rucio/etc/rucio.cfg;
          echo "ca_cert = /etc/ssl/certs/ca-certificates.crt" >> /opt/rucio/etc/rucio.cfg;
          echo "account = <YOUR_ACCOUNT>" >> /opt/rucio/etc/rucio.cfg;
          echo "username = <YOUR_USERNAME>" >> /opt/rucio/etc/rucio.cfg;
          echo "password = <YOUR_PASSWORD>" >> /opt/rucio/etc/rucio.cfg;
          echo "auth_type = userpass" >> /opt/rucio/etc/rucio.cfg;
  extraEnv:
    RUCIO_MODE: "download"
    RUCIO_WILDCARD_ENABLED: "1"
    RUCIO_BASE_URL: "https://rucio-server.212.189.145.181.myip.cloud.infn.it"
    RUCIO_AUTH_URL: "https://rucio-server.212.189.145.181.myip.cloud.infn.it"
    RUCIO_DISPLAY_NAME: "IDL Test Extension"
    RUCIO_NAME: "IDL"
    RUCIO_CA_CERT: "/etc/ssl/certs/ca-certificates.crt"
    JUPYTERHUB_SINGLEUSER_APP: "jupyter_server.serverapp.ServerApp"
  ### Storage is handled by the k8s cluster's local-path-provisioner ###

ingress:
 enabled: true
 annotations:
   nginx.ingress.kubernetes.io/ssl-passthrough: "false"
   nginx.ingress.kubernetes.io/ssl-redirect: "false"
   cert-manager.io/cluster-issuer: letsencrypt-prod-issuer
 ingressClassName: nginx
 hosts:
   - jupyterhub.212.189.145.181.myip.cloud.infn.it
 tls: 
 - hosts:
   - jupyterhub.212.189.145.181.myip.cloud.infn.it
   secretName: jupyterhub-tls

proxy:
 https:
   enabled: false
   hosts:
     - jupyterhub.212.189.145.181.myip.cloud.infn.it
   letsencrypt:
     contactEmail: <YOUR_EMAIL>

hub:
  config:
    Authenticator:
      admin_users:
        - test
    DummyAuthenticator:
      password: <SHARED_PASSWORD>
    JupyterHub:
      authenticator_class: dummy
