# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# replicaCount gives the number of server pods to run
replicaCount: 1

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 1

minReadySeconds: 5

image:
  repository: rucio/rucio-webui
  tag: latest #release-33.0.0
  pullPolicy: Always

imagePullSecrets: []
# - name: docker-regcreds

useSSL: false

proxy:
  rucioProxyScheme: "https"

service:
  type: NodePort
  port: 3000
  targetPort: 3000
  #port: 443
  #targetPort: 443
  protocol: TCP
  name: http
  annotations:
    {}
    # loadbalancer.openstack.org/network-id: "<id>"
    # service.beta.kubernetes.io/openstack-internal-load-balancer: "true"
    # loadbalancer.openstack.org/cascade-delete: "false"
  loadBalancerIP: null
  loadBalancerClass: null
  externalTrafficPolicy: null
  allocateLoadBalancerNodePorts: false

useDeprecatedImplicitSecrets: false

ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    cert-manager.io/cluster-issuer: letsencrypt-prod-issuer
  path: /
  hosts:
    - <WEBUI_HOSTNAME>
  tls:
    - secretName: tls-rucio-webui

secretMounts:
  - secretName: rse-accounts
    mountPath: /opt/rucio/etc/rse-accounts-template.cfg
    subPath: rse-accounts-template.cfg
#   - secretName: ca-cert
#     mountPath: /etc/grid-security/hostcert.pem
#     subPath: hostcert.pem
#   - secretName: ca-cert
#     mountPath: /etc/grid-security/hostkey.pem
#     subPath: hostkey.pem
#   - secretName: ca-bundle
#     mountPath: /etc/pki/ca-trust/source/anchors/ca.pem
#     subPath: ca.pem
#secretMounts: []
# - volumeName: gcssecret
#   secretName: gcssecret
#   mountPath: /opt/rucio/etc/gcs_rucio.json
#   subPath: gcs_rucio.json

config:
  ## values used to configure apache, sets environment variables in the webui container that begin with RUCIO_HTTPD_
  httpd:
    # server_admin: "webmaster@localhost"
    mpm_mode: "event"
    start_servers: "1"
    min_spare_threads: "1"
    max_spare_threads: "20"
    threads_per_child: "5"
    max_clients: "20"
    max_requests_per_child: "8192"
    timeout: 300
    min_spare_servers: "1"
    max_spare_servers: "5"
    server_limit: "10"
    keep_alive: "On"
    keep_alive_timeout: "5"
    max_keep_alive_requests: "128"
    threads_limit: "128"
    max_request_workers: "50" #1280
    max_connections_per_child: "2048"

  ## Rucio WebUI specific configuration for apache
  webui:
    # hostname of the rucio server, include http:// or https://
    rucio_host: https://<RUCIO_SERVER_HOSTNAME>:443
    # hostname of the rucio-auth server, include http:// or https://
    rucio_auth_host: https://<RUCIO_SERVER_HOSTNAME>:443
    # hostname of the webui ( without http:// or https://, just the hostname, no port or scheme required)
    hostname: <WEBUI_HOSTNAME>
    project_url: "https://rucio.cern.ch"
    # if your DID schema in your policy uses special characters like + or /, set this to true
    params_encoding_enabled: "False"
    # if you want to disable userpass authentication, set this to False
    enable_userpass_login: "True"
    # if you want to add your own custom logo to the webui's login page, set this to the url of the logo
    community_logo_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSxnHbkErtMHdMn2FXvsMrkyk55SPeqh4bkB8X4uvAQE2HHNmFznf46Zkr96kN_5EbmFfc&usqp=CAU"
    # to associate a custom Activity to the rules created with the webui, set this to the name of the activity
    rule_activity: "User Subscriptions"
    multivo_enabled: "True"
    # A csv string of vos containing their short names. For example: "def,atl,cms"
    vo_list: "def"
    vo_default: "Default"
    oidc_enabled: "False"
    # A csv string of names of supported oidc providers that will be configured in the webui. For example: "cern,indico"
    oidc_providers: ""
    server_ca_bundle: /etc/grid-security/ca.pem #/etc/pki/ca-trust/source/anchors/ca.pem #

  oidc_providers:
    cern:
      client_id: ""
      client_secret: ""
      authorization_url: ""
      token_url: ""
      refresh_token_url: ""
      userinfo_url: ""
      redirect_url: ""

  vo:
    def:
      name: "Default"
      oidc_enabled: "False"
      oidc_providers: ""
    # Example of a second VO
    # atl:
    #   name: "atlas"
    #   oidc_enabled: "False"
    #   oidc_providers: ""

  logs:
    exposeHttpdLogs: true
    exposeWebuiLogs: true
  
  credentials:
    gcs: "/opt/rucio/etc/rse-accounts-template.cfg"

# additional environment variables to set in the webui container as hardcoded key value pairs
optionalConfig: {}
#  MY_ENV: "my_value"

# hostPathMounts is a list of hostPath mounts to be mounted in the webui container
hostPathMounts: []
# - mountPath: /opt/rucio/etc/aliases.conf
#   hostPath: /etc/rucio/aliases.conf
#   type: DirectoryOrCreate

# additional volumes to be mounted in the webui container from config maps, secrets, etc.
additionalEnvs: []
# - name: MY_ENV
#   value: "my_value"
#   valueFrom:
#     secretKeyRef:
#       name: my-secret
#       key: my-key

persistentVolumes: {}

resources:
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector:
  kubernetes.io/hostname: vnode-7

tolerations: []

affinity: {}
